# Generated by Django 5.2.5 on 2025-08-06 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildathon", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buildathon",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_buildathons",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="buildathon",
            name="registered_participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_buildathons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buildathonjudging",
            name="judge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildathon_judgings",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="buildathonparticipant",
            name="buildathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="buildathon.buildathon",
            ),
        ),
        migrations.AddField(
            model_name="buildathonparticipant",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildathon_participants",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="buildathonquestion",
            name="buildathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="buildathon.buildathon",
            ),
        ),
        migrations.AddField(
            model_name="buildathonsubmission",
            name="buildathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="buildathon.buildathon",
            ),
        ),
        migrations.AddField(
            model_name="buildathonsubmission",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildathon_submissions",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="buildathonsubmission",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="buildathon.buildathonquestion",
            ),
        ),
        migrations.AddField(
            model_name="buildathonjudging",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judgings",
                to="buildathon.buildathonsubmission",
            ),
        ),
        migrations.AddField(
            model_name="buildathonteam",
            name="buildathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="buildathon.buildathon",
            ),
        ),
        migrations.AddField(
            model_name="buildathonteam",
            name="team_members",
            field=models.ManyToManyField(
                blank=True, related_name="buildathon_teams", to="profiles.profile"
            ),
        ),
        migrations.AddField(
            model_name="buildathonwinner",
            name="buildathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winners",
                to="buildathon.buildathon",
            ),
        ),
        migrations.AddField(
            model_name="buildathonwinner",
            name="participant",
            field=models.ForeignKey(
                help_text="Profile of the winner (individual or team member)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildathon_wins",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="buildathonwinner",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team the participant was part of, if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wins",
                to="buildathon.buildathonteam",
            ),
        ),
        migrations.AddField(
            model_name="questionattachment",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="buildathon.buildathonquestion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="buildathonjudging",
            unique_together={("submission", "judge")},
        ),
        migrations.AlterUniqueTogether(
            name="buildathonwinner",
            unique_together={("buildathon", "participant")},
        ),
    ]
