# Generated by Django 5.2.5 on 2025-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuilderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startup_name", models.CharField(max_length=100)),
                ("startup_idea", models.TextField()),
                (
                    "startup_stage",
                    models.CharField(
                        choices=[
                            ("ideation", "Ideation"),
                            ("pre-launch", "Pre-Launch"),
                            ("launched", "Launched"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "startup_category",
                    models.CharField(
                        choices=[
                            ("AI", "AI/ML"),
                            ("FINTECH", "Fintech"),
                            ("EDTECH", "EdTech"),
                            ("HEALTHTECH", "HealthTech"),
                            ("SAAS", "SaaS"),
                            ("WEB3", "Web3"),
                            ("MARKETPLACE", "Marketplace"),
                            ("SOCIAL", "Social Media"),
                            ("GAMING", "Gaming"),
                            ("E_COMMERCE", "E-commerce"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Choose the category that best describes your startup.",
                        max_length=30,
                    ),
                ),
                ("IS_DEPLOYED", models.BooleanField()),
                (
                    "startup_description",
                    models.CharField(
                        choices=[
                            ("INNOVATIVE", "Innovative"),
                            ("SCALABLE", "Scalable"),
                            ("BOOTSTRAPPED", "Bootstrapped"),
                            ("VC_FUNDED", "VC Funded"),
                            ("TEAM_BASED", "Team Based"),
                            ("SOLO_FOUNDER", "Solo Founder"),
                            ("COMMUNITY_DRIVEN", "Community Driven"),
                            ("EXPERIMENTAL", "Experimental"),
                            ("IMPACT_FOCUSED", "Impact Focused"),
                            ("STEALTH", "Stealth Mode"),
                        ],
                        default="INNOVATIVE",
                        help_text="Choose the phrase that best describes your startup.",
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
