# Generated by Django 5.2.5 on 2025-08-06 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Skills",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("joiner", "Joiner"), ("builder", "Builder")],
                        max_length=10,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("is_onboarding_complete", models.BooleanField(default=False)),
                (
                    "experience",
                    models.PositiveIntegerField(
                        blank=True, help_text="Years of experience", null=True
                    ),
                ),
                ("education", models.CharField(blank=True, max_length=255)),
                ("resume_link", models.URLField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("startup_name", models.CharField(blank=True, max_length=255)),
                ("startup_description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("hiring_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillWeightage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weightage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_weightages",
                        to="profiles.profile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.skills",
                    ),
                ),
            ],
            options={
                "ordering": ["-weightage"],
                "unique_together": {("profile", "skill")},
            },
        ),
    ]
