# Generated by Django 5.2.3 on 2025-07-22 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=255, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("builder", "Builder"), ("joiner", "Joiner")],
                        max_length=10,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("Age", models.IntegerField(blank=True, null=True)),
                ("experience", models.IntegerField(blank=True, null=True)),
                ("education", models.TextField(blank=True)),
                ("Projects", models.TextField(blank=True)),
                ("Links", models.TextField(blank=True)),
                (
                    "Resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("Startup_name", models.CharField(blank=True, max_length=255)),
                ("Startup_description", models.TextField(blank=True)),
                ("is_Deployed", models.BooleanField(default=False)),
                ("startup_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillWeightage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weightage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.skills",
                    ),
                ),
            ],
        ),
    ]
