# Generated by Django 5.2.5 on 2025-08-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildathon", "0002_initial"),
        ("challenges", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderchallenge",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_challenges",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="builderchallenge",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills required for this challenge",
                related_name="builder_challenges",
                to="profiles.skills",
            ),
        ),
        migrations.AddField(
            model_name="challengeapplicant",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
        migrations.AddField(
            model_name="challengeapplicant",
            name="buildathon_credentials",
            field=models.ManyToManyField(
                help_text="Buildathon wins that qualify this application",
                to="buildathon.buildathonwinner",
            ),
        ),
        migrations.AddField(
            model_name="challengeapplicant",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.builderchallenge",
            ),
        ),
        migrations.AddField(
            model_name="challengejudging",
            name="judge",
            field=models.ForeignKey(
                limit_choices_to={"role": "builder"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_judged_by",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="challengejudging",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_judged_submissions",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="challengequestion",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="challenges.builderchallenge",
            ),
        ),
        migrations.AddField(
            model_name="challengesubmission",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="challenges.challengeapplicant",
            ),
        ),
        migrations.AddField(
            model_name="challengesubmission",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.challengequestion",
            ),
        ),
        migrations.AddField(
            model_name="challengejudging",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judgings",
                to="challenges.challengesubmission",
            ),
        ),
        migrations.AddField(
            model_name="challengetestcase",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="challenges.challengequestion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengejudging",
            unique_together={("submission", "judge")},
        ),
    ]
